version: "3.8"

services:
    db:
        image: postgres
        container_name: ffy_db
        restart: always
        environment:
            POSTGRES_USER: ffy_user
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: ffy_db
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - ffy-network

    # Redis para memória persistente
    redis:
        image: redis:7-alpine
        container_name: ffy_redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - ffy-network

    # API Principal
    # api:
    #     build: .
    #     container_name: ffy_api
    #     restart: always
    #     environment:
    #         - OPENAI_API_KEY=${OPENAI_API_KEY}
    #         - DATABASE_URL=postgresql://ffy_user:123456@db:5432/ffy_db
    #         - REDIS_URL=redis://redis:6379
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - db
    #         - redis
    #     networks:
    #         - ffy-network

volumes:
    pgdata:
        driver: local
    redis_data:
        driver: local

networks:
    ffy-network:
        driver: bridge
