# version: '3.8'

# services:
#   # API Principal
#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - MONGODB_URI=mongodb://mongo:27017/
#       - MONGODB_DATABASE=ffy_assistant
#       - APP_NAME=FFY Data Assistant
#       - APP_VERSION=1.0.0
#     depends_on:
#       - mongo
#     volumes:
#       - ./logs:/app/logs
#     restart: unless-stopped
#     networks:
#       - ffy-network

#   # MongoDB
#   mongo:
#     image: mongo:6.0
#     ports:
#       - "27017:27017"
#     environment:
#       - MONGO_INITDB_DATABASE=ffy_assistant
#     volumes:
#       - mongo_data:/data/db
#       - ./mongo-init:/docker-entrypoint-initdb.d
#     restart: unless-stopped
#     networks:
#       - ffy-network

#   # MongoDB Express (Interface web opcional)
#   mongo-express:
#     image: mongo-express:latest
#     ports:
#       - "8081:8081"
#     environment:
#       - ME_CONFIG_MONGODB_SERVER=mongo
#       - ME_CONFIG_MONGODB_PORT=27017
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=admin123
#     depends_on:
#       - mongo
#     restart: unless-stopped
#     networks:
#       - ffy-network

# volumes:
#   mongo_data:

# networks:
#   ffy-network:
#     driver: bridge

version: "3.8"

services:
    db:
        image: postgres
        container_name: ffy_db
        restart: always
        environment:
            POSTGRES_USER: ffy_user
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: ffy_db
        volumes:
            - pgdata:/data/postgres
        ports:
            - "5432:5432"

volumes:
    pgdata:
        driver: local

networks:
    ffy-network:
        driver: bridge
